[versions]
#plugins
coreSplashscreen = "1.0.1"
kotlin = "1.9.21"
agp = "8.2.2"

#SDK

compileSdk = "34"
minSdk = "26"
mvikotlin = "3.3.0"
orgJetbrainsComposeGradlePlugin = "1.5.11"
targetSdk = "34"
namespace = "com.markettwits.shift"
jvm = "8"
jvm-dot = "1.8"

#DI
koin = "3.4.0"

# Compose
compose = "1.5.7"
compose-multiplatform = "1.5.11"
compose-ui = "1.5.3"
compose-bom = "2023.03.00"
compose-activity = "1.8.1"
compose-lifecycle = "2.6.1"
compose-material3 = "1.2.0-alpha11"
compose-navigation = "2.7.1"
compose-preview = "1.5.1"
compose-coil = "2.5.0"
accompanist = "0.32.0"
onebone-toolbar = "2.3.5"
realm-gradle-plugin = "10.2.0"
zoomable = "1.5.1"
pullRefresh = "1.2.0"
# Android
android-lifecycle-ktx = "2.6.1"
exifinterface = "1.3.6"

#Ui/Unit test
junit = "4.12"
junit-ext-ktx = "1.1.5"
testing = "6.9.6"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
leakcanary = "2.12"

#Network
core-ktx = "1.9.0"
ktor = "2.2.4"
#UI
appcompat = "1.6.1"
material = "1.9.0"


#Database
realm = "1.11.0"
sqldelight = "2.0.1"
kstore = "0.7.1"
harawata-appdirs = "1.2.1"
#Codegen
ksp = "1.9.22-1.0.16"

#Serialization
kotlinx-serialization = "1.6.2"
jakewharton = "0.8.0"

#Decompose
decompose = "3.0.0-alpha04"
org-jetbrains-kotlin-jvm = "1.9.21"

androidx-appcompat = "1.6.1"
androidx-activityCompose = "1.8.1"
compose-uitooling = "1.5.4"
composeImageLoader = "1.7.1"
kotlinx-coroutines = "1.7.3"

[libraries]
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

compose-ui = { group = "androidx.compose", name = "ui:ui", version.ref = "compose" }
compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-ui" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-ui" }
compose-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "compose-material3" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-ui" }
compose-accomponist = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-preview" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-preview" }
compose-coil = {group = "io.coil-kt", name = "coil-compose", version.ref = "compose-coil"}
compose-icons = {group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-ui"}
pullrefresh = { module = "dev.materii.pullrefresh:pullrefresh", version.ref = "pullRefresh" }

#KMM Compose
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-uitooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-uitooling" }
composeImageLoader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "composeImageLoader" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

#MVI KOTLIN
mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-extensions-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }
mvikotlin-logging = { module = "com.arkivanov.mvikotlin:mvikotlin-logging", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
android-lifecycle-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "android-lifecycle-ktx" }
jetbrains-compose-gradle = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "orgJetbrainsComposeGradlePlugin" }
realm-gradle-plugin = { module = "io.realm:realm-gradle-plugin", version.ref = "realm-gradle-plugin" }
zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }
#androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }

#Test
junit = {group = "junit", name = "junit",version.ref = "junit"}
junit-ext-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit-ext-ktx" }
testing = { group = "org.testng", name = "testing", version.ref = "testing" }

#Serialization
kotlinx-serialization-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlinx-serialization" }
kotlinx-serialization-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization"}
jakewharton = {group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "jakewharton"}

#Data
kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }
kstore-file = { module = "io.github.xxfast:kstore-file", version.ref = "kstore" }
kstore-storage = { module = "io.github.xxfast:kstore-storage", version.ref = "kstore" }
harawata-appdirs = { module = "net.harawata:appdirs", version.ref = "harawata-appdirs" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
realm = {group =  "io.realm.kotlin", name = "library-base", version.ref = "realm"}
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation= { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

#Decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose-jetbrains = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version = "v2.2.0-alpha01" }
decompose-compose-extension = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-compose-jetpack = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }
decompose-android = { module = "com.arkivanov.decompose:extensions-android", version.ref = "decompose"}

#DI
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = {group = "io.insert-koin", name = "koin-android", version.ref = "koin"}

android-gradle = {module = "com.android.tools.build:gradle", version.ref = "agp"}
kotlin-gradle = {module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}

[plugins]
#kotlin-serialization =  {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-serialization =  {id = "org.jetbrains.kotlin.plugin.serialization", version = "1.9.21"}
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = {id = "com.android.application", version.ref = "agp"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"}
realm = {id = "io.realm.kotlin", version.ref = "realm"}
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
sqldelight = {id = "app.cash.sqldelight", version.ref = "sqldelight"}

#Convention Plugins
kotlin-jvm-convention = {id = "kotlin-jvm-convention", version = "unspecified"}
android-library-convention = {id = "android-library-convention", version = "unspecified"}
android-library-compose-convention = {id = "android-library-compose-convention", version = "unspecified"}

#Test Plugins
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
composeUiBundle = [
    "compose-graphics",
    "compose-runtime",
    "compose-lifecycle-viewmodel",
    "compose-activity",
    "compose-material3",
    "compose-material3-window-size",
    "compose-accomponist",
    "pullrefresh",
    "android-lifecycle-ktx",
    "compose-coil",
    "compose-icons"
]
composeUiTest = ["junit-ext-ktx", "testing"]
composeUiBundleDebug = [
    "compose-preview",
    "compose-tooling-preview",
]
decompose-compose = ["decompose-compose-extension", "decompose"]
mviKotlin = ["mvikotlin","mvikotlin-extensions-coroutines","mvikotlin-logging","mvikotlin-main"]

