[versions]
#plugins
calendar = "1.2.1"
coreSplashscreen = "1.0.1"
jwtdecode = "3.18.2"
kotlin = "1.9.23"
gradle = "8.3.2"

#SDK
kotlinxCollectionsImmutable = "0.3.7"
targetSdk = "34"
namespace = "com.markettwits.sportsouce"
minSdk = "26"
compileSdk = "34"
versionName = "1.2.2"
jvm = "8"
jvm-dot = "1.8"

#UI

mvikotlin = "3.3.0"
orgJetbrainsComposeGradlePlugin = "1.6.1"

#DI
koin = "3.5.3"

# Compose
compose = "1.5.11"
compose-ui = "1.6.4"
compose-bom = "2024.03.00"
compose-activity = "1.8.2"
compose-lifecycle = "2.7.0"
compose-material3 = "1.2.1"
compose-preview = "1.6.4"
compose-coil = "2.5.0"
accompanist = "0.34.0"
onebone-toolbar = "2.3.5"
realm-gradle-plugin = "10.2.0"
zoomable = "1.5.1"
pullRefresh = "1.0.1"
lazytable = "1.6.0"
material3HtmlText = "2.0.0-beta01"
compose-markdown = "0.4.1"
# Android
android-lifecycle-ktx = "2.7.0"

#Ui/Unit test
junit = "4.13.2"
junit-ext-ktx = "1.1.5"
testing = "6.9.6"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
leakcanary = "2.12"

#Network
core-ktx = "1.12.0"
ktor = "2.3.8"
#UI
appcompat = "1.6.1"
material = "1.11.0"
lottie = "6.3.0"
orbital = "0.3.4"
libphonenumber = "8.13.31"


#Database
realm = "1.13.0"
kstore = "0.7.2"
#Codegen
ksp = "1.9.22-1.0.17"

#Serialization
kotlinx-serialization = "1.6.2"
kotlinx-coroutines = "1.7.3"

#Decompose
decompose = "3.0.0-alpha04"
org-jetbrains-kotlin-jvm = "1.9.23"

#Tracer
tracer = "0.2.15"

kotlinx-datetime = "0.5.0"
kotlinGradlePlugin = "1.9.0"
kotlinGradlePluginVersion = "1.9.0"

[libraries]
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
calendar = { module = "com.maxkeppeler.sheets-compose-dialogs:calendar", version.ref = "calendar" }
compose-ui = { group = "androidx.compose", name = "ui:ui", version.ref = "compose" }
compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-ui" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-ui" }
compose-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-animation = { group = "androidx.compose.animation", name = "animation", version = "1.7.0-SNAPSHOT" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "compose-material3" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-ui" }
compose-accomponist = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-preview" }
compose-coil = {group = "io.coil-kt", name = "coil-compose", version.ref = "compose-coil"}
compose-icons = {group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-ui"}
jwtdecode = { module = "com.auth0:java-jwt", version.ref = "jwtdecode" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
lazytable = { module = "io.github.oleksandrbalan:lazytable", version.ref = "lazytable" }
material3-html-text = { module = "de.charlex.compose.material3:material3-html-text", version.ref = "material3HtmlText" }
pullrefresh = { module = "eu.bambooapps:compose-material3-pullrefresh", version.ref = "pullRefresh" }
compose-markdown = { group = "com.github.jeziellago", name = "compose-markdown", version.ref = "compose-markdown" }
#MVI KOTLIN
mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-extensions-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }
mvikotlin-logging = { module = "com.arkivanov.mvikotlin:mvikotlin-logging", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
#UI
onebone-toolbar = {group = "me.onebone", name = "toolbar-compose", version.ref = "onebone-toolbar"}
libphonenumber = { group = "com.googlecode.libphonenumber", name = "libphonenumber", version.ref = "libphonenumber" }
orbital = { group = "com.github.skydoves", name = "orbital", version.ref = "orbital" }
android-lifecycle-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "android-lifecycle-ktx" }
org-jetbrains-compose-gradle-plugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "orgJetbrainsComposeGradlePlugin" }
realm-gradle-plugin = { module = "io.realm:realm-gradle-plugin", version.ref = "realm-gradle-plugin" }
zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }

#Test
junit = {group = "junit", name = "junit",version.ref = "junit"}
junit-ext-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit-ext-ktx" }
testing = { group = "org.testng", name = "testing", version.ref = "testing" }


#Serialization
kotlinx-serialization-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlinx-serialization" }
kotlinx-serialization-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization"}
kotlinx-serialization-json = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization"}
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
#Data
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
realm = {group =  "io.realm.kotlin", name = "library-base", version.ref = "realm"}
kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }
kstore-file = { module = "io.github.xxfast:kstore-file", version.ref = "kstore" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

#Network
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation= { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

#Decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
#decompose-compose-jetbrains = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version = "v2.2.0-alpha01" }
decompose-compose-extension = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
#decompose-compose-jetpack = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }
decompose-android = { module = "com.arkivanov.decompose:extensions-android", version.ref = "decompose"}

#DI
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = {group = "io.insert-koin", name = "koin-android", version.ref = "koin"}

#UI
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity = { group = "androidx.activity", name = "activity-ktx", version = "1.8.2" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

#Tracer
tracer-crash-report = { group = "ru.ok.tracer", name = "tracer-crash-report", version.ref = "tracer" }

#Gradle Plugins
android-gradle = {module = "com.android.tools.build:gradle", version.ref = "gradle"}
kotlin-gradle = {module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}
tracer-gradle-plugin = { module = "ru.ok.tracer:ru.ok.tracer.gradle.plugin", version.ref = "tracer" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinGradlePluginVersion" }

[plugins]
#kotlin-serialization =  {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-serialization =  {id = "org.jetbrains.kotlin.plugin.serialization", version = "1.9.10"}
android-library = { id = "com.android.library", version.ref = "gradle" }
android-application = {id = "com.android.application", version.ref = "gradle"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"}
realm = {id = "io.realm.kotlin", version.ref = "realm"}
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }

#Convention Plugins
kotlin-jvm-convention = {id = "kotlin-jvm-convention", version = "unspecified"}
android-library-convention = {id = "android-library-convention", version = "unspecified"}
android-library-compose-convention = {id = "android-library-compose-convention", version = "unspecified"}
kotlin-kmp-convention = { id = "kotlin-multiplatform-convention", version = "unspecified" }

#KMM
kotlin-kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-kmp-compose = { id = "org.jetbrains.compose", version = "1.6.1" }

[bundles]
composeUiBundle = [
    "compose-graphics",
    "compose-runtime",
    "compose-lifecycle-viewmodel",
    "compose-activity",
    "compose-material3",
    "compose-material3-window-size",
    "compose-accomponist",
    "pullrefresh",
    "android-lifecycle-ktx",
    "compose-coil",
    "compose-icons"
]
decompose-compose = ["decompose-compose-extension", "decompose"]
mviKotlin = ["mvikotlin","mvikotlin-extensions-coroutines","mvikotlin-logging","mvikotlin-main"]

