[versions]
#plugins
versionName = "1.5.5"
versionCode = "10420"
jvm = "11"
kotlin = "2.3.10" # https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-compatibility-guide.html#version-compatibility
gradle = "8.12.3" # https://developer.android.com/studio/releases#android_gradle_plugin_and_android_studio_compatibility
compose = "1.10.1" # https://github.com/JetBrains/compose-multiplatform
kotlinx-serialization = "1.10.0" # https://github.com/Kotlin/kotlinx.serialization
kotlinx-coroutines = "1.10.2" # https://github.com/Kotlin/kotlinx.coroutines
kotlinx-datetime = "0.7.1" # https://github.com/Kotlin/kotlinx-datetime
kstore = "1.0.0" # https://github.com/xxfast/KStore
kermit = "2.0.8" # https://kermit.touchlab.co/docs/
koin = "4.1.1" # https://github.com/InsertKoinIO/koin
ktor = "3.4.0" # https://github.com/ktorio/ktor
jetbrainsKotlinWrappers = "2026.2.24" #https://github.com/JetBrains/kotlin-wrappers
compottie = "2.0.3" # https://github.com/alexzhirkevich/compottie
androidxCore = "1.17.0" #https://developer.android.com/jetpack/androidx/releases/core
coreSplashscreen = "1.2.0" # https://developer.android.com/reference/kotlin/androidx/core/splashscreen/SplashScreen
pagingCommon = "3.3.0-alpha02-0.5.1" # https://github.com/cashapp/multiplatform-paging
richeditor = "1.0.0-rc13" # https://github.com/MohamedRejeb/compose-rich-editor
multiplatformMarkdownRendererM3 = "0.39.2" # https://github.com/mikepenz/multiplatform-markdown-renderer
composeMaterial3 = "1.10.0-alpha05" # https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.10.1
composeMaterialIconsExtended = "1.7.3" # https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.10.1
composeMaterial3Adaptive = "1.2.0" # https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive
composeMaterial3WindowSizeClass = "1.9.0" # https://mvnrepository.com/artifact/org.jetbrains.compose.material3/material3-window-size-class
composeMaterial3AdaptiveNavigationSuite = "1.9.0" #https://mvnrepository.com/artifact/org.jetbrains.compose.material3/material3-adaptive-navigation-suite
composeHotReload = "1.0.0" # https://github.com/JetBrains/compose-hot-reload
buildConfigPlugin = "6.0.7" # https://github.com/gmazzo/gradle-buildconfig-plugin
compose-activity = "1.12.4" # https://developer.android.com/jetpack/androidx/releases/activity
compose-preview = "1.10.4" # https://mvnrepository.com/artifact/androidx.compose.ui/ui-tooling-preview
appcompat = "1.7.1" # https://developer.android.com/jetpack/androidx/releases/appcompat
androidxCredentials = "1.5.0" # https://developer.android.com/jetpack/androidx/releases/credentials
decompose = "3.4.0" # https://github.com/arkivanov/Decompose
reaktive = "2.4.0" # https://github.com/badoo/Reaktive
mvikotlin = "4.3.0" # https://github.com/arkivanov/MVIKotlin
tracer = "1.2.2" # https://apptracer.ru/

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core = { module = "androidx.core:core", version.ref = "androidxCore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidxCredentials" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-animation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "compose" }
compose-components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose" }
compose-components-ui-tooling-preview = { group = "org.jetbrains.compose.components", name = "components-ui-tooling-preview", version.ref = "compose" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "composeMaterialIconsExtended" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-preview" }
composeMaterial3WindowSize = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "composeMaterial3WindowSizeClass" }
composeMaterial3Adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "composeMaterial3Adaptive" }
composeMaterial3AdaptiveNavigationSuite = {group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "composeMaterial3AdaptiveNavigationSuite"}
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
coroutines-interop = { module = "com.badoo.reaktive:coroutines-interop", version.ref = "reaktive" }
kotlin-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser" }
richeditor = {group = "com.mohamedrejeb.richeditor", name = "richeditor-compose", version.ref = "richeditor"}
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
multiplatform-markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "multiplatformMarkdownRendererM3" }
mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-extensions-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }
mvikotlin-logging = { module = "com.arkivanov.mvikotlin:mvikotlin-logging", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

jetbrains-kotlinWrappers-kotlinWrappersBom = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-wrappers-bom", version.ref = "jetbrainsKotlinWrappers" }

kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }
kstore-file = { module = "io.github.xxfast:kstore-file", version.ref = "kstore" }
kstore-storage = { module = "io.github.xxfast:kstore-storage", version.ref = "kstore" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

#Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "ktor" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "ktor" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "ktor" }

#Decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose-extension = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
#DI
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }

#Tracer
paging-common = { module = "app.cash.paging:paging-common", version.ref = "pagingCommon" }
paging-compose-common = { module = "app.cash.paging:paging-compose-common", version.ref = "pagingCommon" }
reaktive = { module = "com.badoo.reaktive:reaktive", version.ref = "reaktive" }
tracer-crash-report = { group = "ru.ok.tracer", name = "tracer-crash-report", version.ref = "tracer" }
tracer-crash-report-native = { group = "ru.ok.tracer", name = "tracer-crash-report-native", version.ref = "tracer" }
tracer-heap-dump = { group = "ru.ok.tracer", name = "tracer-heap-dumps", version.ref = "tracer" }
tracer-disk-usage = { group = "ru.ok.tracer", name = "tracer-disk-usage", version.ref = "tracer" }
tracer-profiler-sampling = { group = "ru.ok.tracer", name = "tracer-profiler-sampling", version.ref = "tracer" }

#Kermit
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

#Gradle Plugins
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-multiplatform-gradle-plugin = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-compose-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
org-jetbrains-compose-gradle-plugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }
buildConfigPlugin = { module = "com.github.gmazzo.buildconfig:plugin", version.ref = "buildConfigPlugin" }
tracer-gradle-plugin = { module = "ru.ok.tracer:ru.ok.tracer.gradle.plugin", version.ref = "tracer" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-kmp-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
tracer-android = { id = "ru.ok.tracer", version.ref = "tracer" }
build-konfig = {id = "com.github.gmazzo.buildconfig", version.ref = "buildConfigPlugin"}
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }

#Convention Plugins
kotlin-kmp-convention = { id = "kotlin.multiplatform.convention", version = "unspecified" }
kotlin-kmp-compose-convention = { id = "kotlin.multiplatform.compose.convention", version = "unspecified" }

[bundles]
decompose-compose = ["decompose-compose-extension", "decompose"]
mviKotlin = ["mvikotlin", "mvikotlin-extensions-coroutines", "mvikotlin-logging", "mvikotlin-main"]
