package com.markettwits.edit_profile.edit_profile_Image.presentation.screen

import androidx.compose.runtime.Composable
import com.markettwits.edit_profile.edit_profile_Image.presentation.component.EditProfileImageComponent

@Composable
expect fun NewEditProfileImageScreen(component: EditProfileImageComponent)